### PR TITLE
content/connect: Add the Matrix chat

### PR DESCRIPTION
**Pull request by Conan-Kudo**
### Description

We've had the Matrix chat for quite some time, but we have not really told anyone about it, which has made the usage of it quite low.

Hopefully this helps advertise that we do have a chat for those who want it.
 
### Issues Resolved

N/A

### Check List
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by madolson — APPROVED** [review]
I honestly did not know this page existed. @stockholmux Do we want to refresh this page more generally?

**Comment by melroy89** [comment]
> I honestly did not know this page existed. 

I did .. I couldn't find Matrix or Slack mentioned here. Which was a shame. Eventually found my way around it.

**Review by melroy89 — COMMENTED** [review]
Links works. And it points correctly to the Matrix space, rather than a single room. Great!

**Comment by madolson** [comment]
Well, we'll keep this at the very least so going to merge it.

**Pull request merged**
